sudo: required
services: 
  - docker

before_install: 
  - docker build -t kaiorosa/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true kaiorosa/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-2-905418378139"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_ACCESS_KEY_SECRET"